name: Terraform Deployment with Checkov

on:
  push:
    branches:
      - none  # Trigger on push to main branch
  workflow_dispatch:
    inputs:
      resourcetype:
        description: 'resourcetype to deploy (e.g., VM, Webapp)'
        required: true

jobs:
  terraform-deployment:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: ${{ github.workspace }}/${{ github.event.inputs.resourcetype }}  # Correct working directory
      TF_VERSION: '1.3.5'  # Specify the Terraform version
      BUILD_NUMBER: ${{ github.run_id }}  # Use GitHub's run ID as the build number

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: List the contents of the working directory (for debugging)
    - name: List Working Directory
      run: |
        echo "Listing the contents of the working directory..."
        ls -al $GITHUB_WORKSPACE

    # Step 3: Install Terraform
    - name: Install Terraform ${{ env.TF_VERSION }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: |
        echo "Initializing Terraform..."
        terraform -chdir=${{ env.TF_WORKING_DIR }} init -upgrade

    # Step 5: Run Checkov for Terraform code security analysis
    - name: Run Checkov on Terraform code
      run: |
        echo "Running Checkov for security analysis on Terraform configuration..."
        pip install checkov  # Install Checkov
        # Use the GITHUB_RUN_ID as the build number
        BUILD_NUMBER=${{ github.run_id }}
        # Run Checkov and save the output to a file with the build number in the filename
        checkov -d ${{ env.TF_WORKING_DIR }} -o json > "checkov_output_${BUILD_NUMBER}.json"
        # Copy the output file to the repo directory for later use
        cp "checkov_output_${BUILD_NUMBER}.json" ${{ github.workspace }}/checkov_output_${BUILD_NUMBER}.json
        echo "Checkov output saved successfully."

    # Step 6: Validate Terraform configuration
    - name: Terraform Validate
      run: |
        echo "Validating Terraform configuration..."
        terraform -chdir=${{ env.TF_WORKING_DIR }} validate

    # Step 7: Terraform Plan with environment-specific variables
    - name: Terraform Plan
      run: |
        echo "Running Terraform Plan with environment-specific tfvars..."
        ENV_TFVARS="${{ github.event.inputs.resourcetype }}/terraform.tfvars"
        echo "Using environment-specific tfvars file: ${ENV_TFVARS}"
    
        # Run Terraform Plan with the correct path to tfvars file
        terraform -chdir=${{ env.TF_WORKING_DIR }} plan -out=tfplan -var-file=${{ github.workspace }}/${ENV_TFVARS}

    # Step 8: Remove terraform.lock.hcl file after applying (for clean-up)
    - name: Remove terraform.lock.hcl
      run: |
        echo "Removing terraform.lock.hcl after applying..."
        rm -f ${{ env.TF_WORKING_DIR }}/terraform.lock.hcl

    # Step 9: Commit the Checkov output file to the repository
    - name: Commit Checkov output to the repository
      run: |
        echo "Configuring Git..."
        git config --global user.email "sivalakshmimettu@github.com"
        git config --global user.name "sivalakshmimettu"
        git config --global core.safeDirectory "${GITHUB_WORKSPACE}"  # Ensuring safe directory

        echo "Adding Checkov output to git..."
        git add checkov_output_${{ env.BUILD_NUMBER }}.json
        
        echo "Committing Checkov output..."
        git commit -m "Add Checkov security scan output with build number ${BUILD_NUMBER}"
        
        echo "Pushing changes..."
        git push origin HEAD:${{ github.ref }}
